services:
  salt-rim:
    container_name: salt-rim
    image: barassistant/salt-rim:v2
    environment:
      - API_URL=$API_URL
      - MEILISEARCH_URL=$MEILISEARCH_URL
      - DEFAULT_LOCALE=en-US
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - 8080
    networks:
      proxy_net:
#
  bar-assistant:
    container_name: bar-assistant
    image: barassistant/server:v3
    depends_on:
      meilisearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - APP_URL=$API_URL
      - LOG_CHANNEL=stderr
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - MEILISEARCH_HOST=http://meilisearch:7700
      - REDIS_HOST=redis
# add users
      - ALLOW_REGISTRATION=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./bar_data:/var/www/cocktails/storage/bar-assistant
    expose:
      - 3000
    networks:
      proxy_net:
#
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.4
    environment:
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - MEILI_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./meilisearch_data:/meili_data
    expose:
      - 7700
    networks:
      proxy_net:
#
  redis:
    container_name: redis
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    expose:
      - 6379
    networks:
      proxy_net:
##
##
networks:
  proxy_net:
    external: true
